"""Canonical catalog of every metric the app understands.

The catalog is the single source of truth for: what dimensions exist, how to
display them, what unit they use, which direction is "good", and which is the
finest geographic level at which the value is meaningfully resolvable.

When the resolver is asked for a metric at a level finer than `finest_level`
it cascades up to the parent (e.g. asking for state income tax at a city
returns the state's tax — the city inherits).
"""

from __future__ import annotations

from dataclasses import dataclass

from .models.metric import MetricDirection


@dataclass(frozen=True)
class MetricDef:
    key: str
    label: str
    category: str
    unit: str
    direction: MetricDirection
    description: str
    source_label: str
    finest_level: str  # state | county | place


CATALOG: list[MetricDef] = [
    # ───── Taxes (mostly state-level — counties/places inherit) ─────
    MetricDef(
        key="tax.income.top_marginal",
        label="Top marginal state income tax",
        category="taxes",
        unit="%",
        direction=MetricDirection.lower_better,
        description="Top marginal personal income tax rate at the state level.",
        source_label="Tax Foundation (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="tax.income.flat_or_progressive",
        label="Income tax structure",
        category="taxes",
        unit="text",
        direction=MetricDirection.target,
        description="None / Flat / Progressive.",
        source_label="Tax Foundation (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="tax.sales.combined_avg",
        label="Combined sales tax (state+local avg)",
        category="taxes",
        unit="%",
        direction=MetricDirection.lower_better,
        description="State sales tax plus average local sales tax.",
        source_label="Tax Foundation (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="tax.property.effective_rate",
        label="Effective property tax rate",
        category="taxes",
        unit="%",
        direction=MetricDirection.lower_better,
        description="Median property tax as % of median home value (state avg). "
        "County values overlay this when available.",
        source_label="Census ACS / Tax Foundation",
        finest_level="county",
    ),
    MetricDef(
        key="tax.estate.has_estate_tax",
        label="State estate or inheritance tax",
        category="taxes",
        unit="bool",
        direction=MetricDirection.lower_better,
        description="1 if the state levies an estate or inheritance tax, else 0.",
        source_label="Tax Foundation (curated)",
        finest_level="state",
    ),
    # ───── Housing (Census ACS — finest at place) ─────
    MetricDef(
        key="housing.median_value",
        label="Median home value",
        category="housing",
        unit="$",
        direction=MetricDirection.target,
        description="Median value of owner-occupied housing units. ACS B25077.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="housing.median_rent",
        label="Median gross rent",
        category="housing",
        unit="$/mo",
        direction=MetricDirection.lower_better,
        description="Median gross rent (rent + utilities). ACS B25064.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="housing.owner_occupied_pct",
        label="Owner-occupied housing rate",
        category="housing",
        unit="%",
        direction=MetricDirection.higher_better,
        description="Share of occupied housing that is owner-occupied. ACS B25003.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    # ───── Cost of living ─────
    MetricDef(
        key="col.rpp",
        label="Regional Price Parity",
        category="cost_of_living",
        unit="index (US=100)",
        direction=MetricDirection.lower_better,
        description="BEA Regional Price Parity — overall price level relative to US avg (100). Metro counties use MSA-level RPP; non-metro counties use state-level.",
        source_label="BEA MARPP (metro) / SARPP (state)",
        finest_level="county",
    ),
    MetricDef(
        key="col.grocery_index",
        label="Goods / grocery price index",
        category="cost_of_living",
        unit="index (US=100)",
        direction=MetricDirection.lower_better,
        description="BEA RPP goods component — price level of consumer goods (groceries, clothing, "
        "household items) relative to US average (100). Ranges from ~93 (AR, MS) to ~114 (HI).",
        source_label="BEA RPP Goods (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="col.childcare_infant_annual",
        label="Infant center-based care (annual)",
        category="cost_of_living",
        unit="$/yr",
        direction=MetricDirection.lower_better,
        description="Annual cost of full-time center-based infant care. "
        "Ranges from ~$6,800 (MS) to ~$24,200 (DC).",
        source_label="Child Care Aware of America",
        finest_level="state",
    ),
    MetricDef(
        key="col.healthcare_marketplace_monthly",
        label="Marketplace health premium (age 40)",
        category="cost_of_living",
        unit="$/mo",
        direction=MetricDirection.lower_better,
        description="2024 benchmark silver plan monthly premium for a 40-year-old non-smoker, "
        "unsubsidized. Reflects underlying healthcare cost levels by state. "
        "Ranges from $344/mo (UT) to $808/mo (WY).",
        source_label="KFF / CMS (curated)",
        finest_level="state",
    ),
    # ───── Climate ─────
    MetricDef(
        key="climate.jan_low_f",
        label="January average low",
        category="climate",
        unit="°F",
        direction=MetricDirection.target,
        description="Mean daily minimum temperature in January (1991–2020 normals).",
        source_label="NOAA NClimDiv (county)",
        finest_level="county",
    ),
    MetricDef(
        key="climate.jul_high_f",
        label="July average high",
        category="climate",
        unit="°F",
        direction=MetricDirection.target,
        description="Mean daily maximum temperature in July (1991–2020 normals).",
        source_label="NOAA NClimDiv (county)",
        finest_level="county",
    ),
    MetricDef(
        key="climate.annual_precip_in",
        label="Annual precipitation",
        category="climate",
        unit="in",
        direction=MetricDirection.target,
        description="Mean annual precipitation (1991–2020 normals).",
        source_label="NOAA NClimDiv (county)",
        finest_level="county",
    ),
    MetricDef(
        key="climate.annual_snowfall_in",
        label="Annual snowfall",
        category="climate",
        unit="in",
        direction=MetricDirection.target,
        description="Mean annual snowfall (1991–2020 normals). County-level from GHCN station normals.",
        source_label="NOAA NCEI Normals (county)",
        finest_level="county",
    ),
    MetricDef(
        key="climate.annual_sunny_days",
        label="Sunny days per year",
        category="climate",
        unit="days",
        direction=MetricDirection.higher_better,
        description="Estimated annual days with clear or few-cloud skies (1991–2020 ASOS hourly normals). County-level from first-order weather stations; ~400 counties covered directly.",
        source_label="NOAA NCEI Hourly Normals (county)",
        finest_level="county",
    ),
    MetricDef(
        key="climate.avg_wind_speed_mph",
        label="Average wind speed",
        category="climate",
        unit="mph",
        direction=MetricDirection.target,
        description="Mean annual wind speed (1991–2020 hourly normals). County-level from first-order ASOS stations; ~400 counties covered directly.",
        source_label="NOAA NCEI Hourly Normals (county)",
        finest_level="county",
    ),
    MetricDef(
        key="hazard.fema_nri",
        label="FEMA National Risk Index",
        category="climate",
        unit="0–100",
        direction=MetricDirection.lower_better,
        description="Composite natural-hazard risk score (0 lowest, 100 highest).",
        source_label="FEMA NRI (curated)",
        finest_level="county",
    ),
    # ───── Crime (FBI CDE — state-level estimates) ─────
    MetricDef(
        key="crime.violent_per_100k",
        label="Violent crime",
        category="crime",
        unit="per 100k",
        direction=MetricDirection.lower_better,
        description="Annual violent-crime estimate per 100,000 population.",
        source_label="FBI UCR (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="crime.property_per_100k",
        label="Property crime",
        category="crime",
        unit="per 100k",
        direction=MetricDirection.lower_better,
        description="Annual property-crime estimate per 100,000 population.",
        source_label="FBI UCR (curated)",
        finest_level="state",
    ),
    # ───── Employment (BLS LAUS) ─────
    MetricDef(
        key="employment.unemployment_rate",
        label="Unemployment rate",
        category="employment",
        unit="%",
        direction=MetricDirection.lower_better,
        description="Most recent annual-average unemployment rate (BLS LAUS).",
        source_label="BLS LAUS",
        finest_level="county",
    ),
    # ───── Demographics & quality of life (Census ACS) ─────
    MetricDef(
        key="pop.total",
        label="Population",
        category="demographics",
        unit="people",
        direction=MetricDirection.target,
        description="Total population. ACS B01003.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="pop.median_age",
        label="Median age",
        category="demographics",
        unit="years",
        direction=MetricDirection.target,
        description="Median age of all residents. ACS B01002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="econ.median_household_income",
        label="Median household income",
        category="demographics",
        unit="$",
        direction=MetricDirection.higher_better,
        description="Median household income (inflation-adjusted). ACS B19013.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="edu.bachelors_or_higher_pct",
        label="Bachelor's degree or higher",
        category="demographics",
        unit="%",
        direction=MetricDirection.higher_better,
        description="Share of population 25+ with a bachelor's degree or higher. ACS B15003.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="housing.insurance_avg_premium",
        label="Average homeowners insurance",
        category="housing",
        unit="$/yr",
        direction=MetricDirection.lower_better,
        description="Average annual homeowners insurance premium for a typical owner-occupied home. "
        "Varies dramatically with hurricane / wildfire / hail exposure.",
        source_label="III / NAIC (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="tax.retirement.burden_score",
        label="Retirement-income tax burden",
        category="taxes",
        unit="0–3",
        direction=MetricDirection.lower_better,
        description="0 = no state income tax, 1 = exempts SS + most pensions, 2 = partial exemption, "
        "3 = taxes most retirement income at ordinary rates.",
        source_label="Tax Foundation / Kiplinger (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="tax.capital_gains.top_rate",
        label="Top long-term capital gains rate (state)",
        category="taxes",
        unit="%",
        direction=MetricDirection.lower_better,
        description="Effective top state long-term capital-gains rate, after notable LTCG exclusions where applicable.",
        source_label="Tax Foundation (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="tax.property.median_annual_bill",
        label="Median annual property tax bill",
        category="taxes",
        unit="$/yr",
        direction=MetricDirection.lower_better,
        description="Median real-estate taxes paid by owner-occupied households. ACS B25103.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="housing.appreciation_10yr_cagr",
        label="10-year home price appreciation",
        category="housing",
        unit="%",
        direction=MetricDirection.target,
        description="10-year compound annual growth rate of home prices (FHFA HPI, all-transactions).",
        source_label="FHFA HPI (county)",
        finest_level="county",
    ),
    MetricDef(
        key="hazard.hurricane",
        label="Hurricane risk",
        category="climate",
        unit="0–100",
        direction=MetricDirection.lower_better,
        description="Tropical cyclone / hurricane component of FEMA NRI (0 lowest, 100 highest).",
        source_label="FEMA NRI (curated)",
        finest_level="county",
    ),
    MetricDef(
        key="hazard.wildfire",
        label="Wildfire risk",
        category="climate",
        unit="0–100",
        direction=MetricDirection.lower_better,
        description="Wildfire component of FEMA NRI.",
        source_label="FEMA NRI (curated)",
        finest_level="county",
    ),
    MetricDef(
        key="hazard.tornado",
        label="Tornado risk",
        category="climate",
        unit="0–100",
        direction=MetricDirection.lower_better,
        description="Tornado component of FEMA NRI.",
        source_label="FEMA NRI (curated)",
        finest_level="county",
    ),
    MetricDef(
        key="hazard.flood",
        label="Flood risk",
        category="climate",
        unit="0–100",
        direction=MetricDirection.lower_better,
        description="Riverine + coastal flood components of FEMA NRI (combined).",
        source_label="FEMA NRI (curated)",
        finest_level="county",
    ),
    MetricDef(
        key="env.pm25_annual",
        label="PM2.5 annual mean",
        category="climate",
        unit="µg/m³",
        direction=MetricDirection.lower_better,
        description="Annual mean fine-particulate concentration averaged across monitors. "
        "WHO guideline 5 µg/m³, US NAAQS 9 µg/m³. Counties with no monitor use state value.",
        source_label="EPA AQS",
        finest_level="county",
    ),
    MetricDef(
        key="climate.summer_heat_index_f",
        label="Summer afternoon heat index",
        category="climate",
        unit="°F",
        direction=MetricDirection.target,
        description="Approximate July afternoon heat index combining mean temperature and humidity. "
        "State-wide average; coastal/southern states feel hotter than dry desert states even at similar temps.",
        source_label="NOAA NCEI Normals (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="utility.electricity_rate",
        label="Residential electricity rate",
        category="utilities",
        unit="¢/kWh",
        direction=MetricDirection.lower_better,
        description="Average residential electricity price.",
        source_label="EIA Form 861 (county)",
        finest_level="county",
    ),
    MetricDef(
        key="infra.broadband_100_20_pct",
        label="Broadband access",
        category="utilities",
        unit="%",
        direction=MetricDirection.higher_better,
        description="Share of households with a broadband internet subscription (cable, fiber, DSL, or satellite).",
        source_label="Census ACS B28002 (county)",
        finest_level="county",
    ),
    MetricDef(
        key="infra.airport_hub_distance_mi",
        label="Distance to large-hub airport",
        category="infrastructure",
        unit="mi",
        direction=MetricDirection.lower_better,
        description="Great-circle distance from the location centroid to the nearest FAA large-hub airport.",
        source_label="FAA hub list / computed",
        finest_level="place",
    ),
    MetricDef(
        key="edu.k12_proficiency_pct",
        label="K-12 reading proficiency (4th grade)",
        category="demographics",
        unit="%",
        direction=MetricDirection.higher_better,
        description="Share of 4th-graders scoring at or above proficient on NAEP reading.",
        source_label="NAEP (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="edu.homeschool_regulation_level",
        label="Homeschool regulation level",
        category="demographics",
        unit="1–5",
        direction=MetricDirection.lower_better,
        description=(
            "How heavily state law regulates home education: "
            "1=no notice required (most permissive), "
            "2=notice only, "
            "3=notice + required subjects or assessments, "
            "4=notice + subjects + testing + teacher qualifications, "
            "5=prior approval required (most restrictive)."
        ),
        source_label="HSLDA State Law Summary (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="edu.school_voucher_program",
        label="School voucher / ESA program",
        category="demographics",
        unit="0–2",
        direction=MetricDirection.higher_better,
        description=(
            "Availability of publicly funded school-choice programs: "
            "0=no meaningful program, "
            "1=limited or means-tested voucher, ESA, or tax-credit scholarship, "
            "2=broad or universal ESA/voucher available to most families."
        ),
        source_label="EdChoice Yearbook 2024 (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="health.primary_care_per_100k",
        label="Primary-care physicians",
        category="health",
        unit="per 100k",
        direction=MetricDirection.higher_better,
        description="Active primary-care physicians per 100,000 population.",
        source_label="HRSA AHRF (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="health.life_expectancy_years",
        label="Life expectancy at birth",
        category="health",
        unit="years",
        direction=MetricDirection.higher_better,
        description="Period life expectancy at birth (composite quality-of-life signal).",
        source_label="CDC NCHS (curated)",
        finest_level="state",
    ),
    MetricDef(
        key="pop.growth_5yr_pct",
        label="5-year population growth",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Cumulative population change 2019–2024 (Census Population Estimates).",
        source_label="Census PEP / BLS QCEW",
        finest_level="county",
    ),
    MetricDef(
        key="employment.job_growth_5yr_pct",
        label="5-year job growth",
        category="employment",
        unit="%",
        direction=MetricDirection.higher_better,
        description="Cumulative employment change 2019–2024 (BLS QCEW annual avg).",
        source_label="Census PEP / BLS QCEW",
        finest_level="county",
    ),
    MetricDef(
        key="politics.partisan_lean_2024",
        label="Partisan lean (2024)",
        category="politics",
        unit="ppts",
        direction=MetricDirection.target,
        description="2024 presidential margin in percentage points; positive = Republican, negative = Democratic.",
        source_label="MIT Election Lab",
        finest_level="county",
    ),
    MetricDef(
        key="demo.race.white_pct",
        label="White (non-Hispanic)",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Share of population that is White alone, not Hispanic or Latino. ACS B03002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="demo.race.black_pct",
        label="Black or African American (non-Hispanic)",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Share of population that is Black or African American alone, not Hispanic or Latino. ACS B03002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="demo.race.hispanic_pct",
        label="Hispanic or Latino (any race)",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Share of population that is Hispanic or Latino, of any race. ACS B03002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="demo.race.asian_pct",
        label="Asian (non-Hispanic)",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Share of population that is Asian alone (includes Asian Indian, Chinese, Filipino, etc.), not Hispanic or Latino. ACS B03002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="demo.race.native_american_pct",
        label="American Indian / Alaska Native (non-Hispanic)",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Share of population that is American Indian or Alaska Native alone, not Hispanic or Latino. ACS B03002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    MetricDef(
        key="demo.race.other_pct",
        label="Other / multiracial (non-Hispanic)",
        category="demographics",
        unit="%",
        direction=MetricDirection.target,
        description="Share of population that is Native Hawaiian/Pacific Islander, some other race alone, "
        "or two or more races, all non-Hispanic. ACS B03002.",
        source_label="Census ACS 5-year",
        finest_level="place",
    ),
    # ───── Health — obesity & cancer (county-level) ─────
    MetricDef(
        key="health.obesity_pct",
        label="Adult obesity prevalence",
        category="health",
        unit="%",
        direction=MetricDirection.lower_better,
        description="Share of adults with BMI ≥ 30 (age-adjusted). "
        "County-level model-based estimates. National average ~33 %.",
        source_label="CDC PLACES 2025",
        finest_level="county",
    ),
    MetricDef(
        key="health.cancer_incidence_per_100k",
        label="Cancer incidence rate",
        category="health",
        unit="per 100k",
        direction=MetricDirection.lower_better,
        description="Age-adjusted all-sites cancer incidence, 2018–2022 (cases per 100,000). "
        "Counties with < ~16 cases/year are suppressed. National avg ~449.",
        source_label="NCI / CDC State Cancer Profiles",
        finest_level="county",
    ),
    MetricDef(
        key="health.cancer_mortality_per_100k",
        label="Cancer mortality rate",
        category="health",
        unit="per 100k",
        direction=MetricDirection.lower_better,
        description="Age-adjusted all-sites cancer mortality, 2019–2023 (deaths per 100,000). "
        "Counties with < ~16 deaths/year are suppressed. National avg ~145.",
        source_label="NCI / CDC State Cancer Profiles",
        finest_level="county",
    ),
    # ───── Environment — public lands & elevation (county-level) ─────
    MetricDef(
        key="env.public_land_pct",
        label="Public land share",
        category="environment",
        unit="%",
        direction=MetricDirection.higher_better,
        description="Share of county land area managed as Federal, State, Tribal, or Joint public land "
        "(BLM, National Forest, National Park, State Parks, etc.). "
        "Source: PAD-US 3.0 clipped to Census 2020 county boundaries.",
        source_label="USGS PAD-US 3.0",
        finest_level="county",
    ),
    MetricDef(
        key="env.elevation_ft",
        label="Elevation (county centroid)",
        category="environment",
        unit="ft",
        direction=MetricDirection.target,
        description="Elevation in feet at the 2020 Census population centroid of the county. "
        "Proxy for altitude / mountainousness; does not capture elevation range within the county.",
        source_label="USGS 3DEP EPQS",
        finest_level="county",
    ),
]


CATALOG_BY_KEY: dict[str, MetricDef] = {m.key: m for m in CATALOG}
